#!/usr/bin/env bash

if [ "$#" -ne 1 ]; then
  echo "Usage: headerify.sh <input-path>"
  exit 1;
fi

input_path="$1"

echo "//auto-generated by headerify.sh"

while IFS='' read -r line || [[ -n "$line" ]]; do
  echo -n "\""
  echo -n "$line" | sed -e 's:":\\":g' | tr -d '\n'
  echo "\\n\""
done < "$input_path"
